web:
  image: nginx:latest
  ports:
    - "9081:80"
  expose:
    - "80"
    - "443"
  hostname: certifiedmuffler
  environment:
    VIRTUAL_HOST: certifiedmuffler.com
    LETSENCRYPT_HOST: certifiedmuffler.com
    LETSENCRYPT_EMAIL: roger2014jr@gmail.com

  volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ~/certifiedmuffler.com/public_html:/var/www/html:rw
  links:
    - php


php:
  build: ./php/
  expose: 
    - "9000"
  volumes:
    - ~/certifiedmuffler.com/public_html:/var/www/html:rw
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"

cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest