web:
  image: nginx:latest
  ports:
    - "9084:80"
  expose:
    - "80"
    - "443"
  hostname: spoilernation
  environment:
    VIRTUAL_HOST: spoilernation.com
    LETSENCRYPT_HOST: spoilernation.com
    LETSENCRYPT_EMAIL: website@directcartrim.com

  volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ~/spoilernation.com/public_html:/var/www/html:rw
  links:
    - php


php:
  build: ./php/
  expose: 
    - "9000"
  volumes:
    - ~/spoilernation.com/public_html:/var/www/html:rw
  links:
  - "cache:rediscache"
  - "sessions:redissession"
  - "fullpagecache:redisfullpagecache"

cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest
