web:
  image: nginx:latest
  ports:
    - "9082:80"
  expose:
    - "80"
    - "443"
  hostname: mareagear
  #environment:
    #VIRTUAL_HOST: newsite.mareagear.com
    #LETSENCRYPT_HOST: newsite.mareagear.com
    #LETSENCRYPT_EMAIL: website@directcartrim.com

  volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ~/mareagear.com/public_html:/var/www/html:rw
  links:
    - php


php:
  build: ./php/
  expose: 
    - "9000"
  volumes:
    - ~/mareagear.com/public_html:/var/www/html:rw
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"

cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest